[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
sha2 = "0.10.8"
error.path = "../error"
lettre.workspace = true
tera = "1.20.0"
anyhow = "1.0.90"
dotenv = "0.15.0"
