//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::group::Entity as Group;
pub use super::message::Entity as Contact;
pub use super::user::Entity as User;
pub use super::user_friend::Entity as UserFriend;
pub use super::user_group::Entity as UserGroup;
